### ISSUE TITLE
Unable to Connect to Development Server via IP

### ISSUE THREAD

**Issue by farhanmeo** [saheeranas/react-native-redux-boilerplate#100]
Description:
I am encountering an issue while trying to run my React Native project on my mobile device via IP. The error message I'm receiving is "Could not connect to development server." I've tried several troubleshooting steps, but the problem persists.

Steps to Reproduce:

    Run the React Native project.
    Attempt to connect to the development server via IP on a mobile device.
    Observe the "Could not connect to development server" error.

Environment:

    React Native version: 0.72.5
    Operating System: Ubuntu
    Node.js version: 16.20.2
    npm version: 8.19.4

Troubleshooting Steps Taken:

    Checked network connection to ensure both devices are on the same network.
    Disabled firewall and antivirus software temporarily.
    Verified correct local IP address.
    Ensured project dependencies are up to date.
    Restarted Metro Bundler.
    Cleared Metro Bundler cache.
    Checked for errors in the Metro Bundler terminal.
    Updated React Native CLI globally.
    Verified correct IP configuration in React Native code.
    Enabled "Developer Options" and "USB Debugging" on the mobile device.

**Comment by saheeranas** [comment]
Hi @farhanmeo,

You can sort out this issue by removing the below line from [/android/app/src/main/AndroidManifest.xml](https://github.com/saheeranas/react-native-redux-boilerplate/blob/main/android/app/src/main/AndroidManifest.xml) file

 `android:networkSecurityConfig="@xml/network_security_config"`

Hope this helps
