### ISSUE TITLE
Even though I followed all the instructions, the icon does not change

### ISSUE THREAD

**Issue by qaniqani** [saheeranas/react-native-redux-boilerplate#116]
Hi everybody.

I integrated Onesignal into my react-native application and it works without any problems. I changed the app icon, created my icons from the github project recommended by onesignal and added them to my project. The icons appear in place in the emulator. But on my real device (Xiaomi mi 11T Pro), the character a appears somewhere in the notification window and this character does not exist in my project. I tried everything, I couldn't understand where it was coming from and how.

Is there anyone who can help with this?

Note: When I send the icon name parametrically from the Onesignal panel, the large icon appears on the right, but the small icon does not appear at all.

![resim](https://github.com/saheeranas/react-native-redux-boilerplate/assets/19714568/44f2d0d1-7c1f-4abf-902a-949e46aac6dd)

**Comment by saheeranas** [comment]
> the character a appears somewhere in the notification window and this character does not exist in my project.

If you are referring to the icon you rounded in the left side (black letter 'alpha' on light yellow), it is the app icon for the debug version of the app, check the codebase [here](https://github.com/saheeranas/react-native-redux-boilerplate/blob/main/android/app/src/debug/res/mipmap-hdpi/ic_launcher.png). It won't show on release version. If it causing any issues (because of caching et al), feel free to replace them (from all 'mipmap' folders) with any other images.

**Comment by saheeranas** [comment]
Other issues sound like something to do with your OneSignal configuration. Please let me know if you find a solution

**Comment by qaniqani** [comment]
Unfortunately, I made all the icon changes. The icons are correct in the emulator, IOS etc. In the Release version, this yellow icon appears again. I looked all over the project and I can't find this icon anywhere, but it appears again in the release version. I no longer think that the problem is caused by onesignal because it belongs to the icon set in boilerplate and I cannot find it in boilerplate. It's been 5 days and I'm about to go crazy :)

**Comment by qaniqani** [comment]
No problem, I authorize you in the repository

**Comment by saheeranas** [comment]
Hi @qaniqani, I checked the project (both debug and release builds). The notification is working fine. The Old icon is not showing up on anywhere. I think your code is fine. 

Please make sure you cleared all the caches before making a new build:
- Clean Android build (`cd android && gradle clean` or clean from android studio)
- Start metro server with reset flag (npx react-native start --reset-cache)
- Uninstall old installed version of the app from the device
- Delete any `index.android.bundle` files which exist in anywhere in the project
- Make a new release build
- Check

If problem persists even after doing all the steps, I suggest you to push all the changes to Git, Backup your signing key, Delete the project from your machine, Clone and build again.  

Device: Redmi 6A
Please check the screenshots 
![Screenshot_2024-06-11-18-02-27-184_com miui home](https://github.com/saheeranas/react-native-redux-boilerplate/assets/9930618/a7157bc3-42ee-436d-8030-dc07bdd61e34)

**Comment by qaniqani** [comment]
Thank you, I will check and let you know again. I was very happy with your help.

**Comment by qaniqani** [comment]
hello again,
Unfortunately it didn't fix it, my personal phone is 11t pro. I did a deep clean on my device but it still didn't work. I think there is a problem with my device. I will find an alternative device and try it there. I will let you know again. Thank you very much for now.
